version: "3.8"

services:
  node_app:
    image: medipro
    container_name: medipro_app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - "5002:5002"

    command: yarn start
