services:
  server:
    image: voldemort69/medipro
    container_name: medipro_server
    restart: always
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - migrate
      - redis

    env_file:
      - .env

  db:
    image: postgres
    restart: always
    container_name: medipro_db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  migrate:
    image: voldemort69/medipro
    container_name: medipro_migrate
    working_dir: /app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: npx prisma migrate deploy

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - 6379:6379

volumes:
  postgres:
  redis:
