services:
  node_app:
    image: voldemort69/medipro
    container_name: medipro_app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3500:3500"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/medipro_db

    command: >
      sh -c "npx prisma migrate deploy && yarn start"

  db:
    image: postgres
    restart: always
    container_name: medipro_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: medipro_db
    volumes:
      - postgres:/var/lib/postgresql/data
    # networks:
    #   - mynetwork

  # adminer:
  #   image: adminer
  #   container_name: my_adminer
  #   ports:
  #     - "8080:8080"
  # networks:
  #   - mynetwork

volumes:
  postgres:
# networks:
#   mynetwork:
#     driver: bridge
