name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 and pull latest code, build and run the Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the application directory
            cd /code/medipro

            # Pull the latest code from the main branch
            git pull origin main

            yarn

            yarn run build

            pm2 stop medipro-server || true  # Stop the app if it's already running
            pm2 start dist/src/app.js --name medipro-server  # Adjust the path to your compiled JS entry file
            pm2 save  # Save the PM2 process list
